services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - 5432:5432
    networks:
      - dokploy-network
    volumes:
      - pgdata:/var/lib/postgresql/data
  next-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    networks:
      - dokploy-network
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  memcached:
    image: memcached:1.6
    ports:
      - 11211:11211
    networks:
      - dokploy-network
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - dokploy-network
    depends_on:
      - db
volumes:
  pgdata:

networks:
  dokploy-network:
    external: true